name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        uses: microsoft/vs-build-tools/setup-cmake@v1
        with:
          cmake-version: '3.21.x'

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
