name: Locgic-Circuit-Simulator-DD1
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        uses: cmake/setup-cmake@v2
        with:
          cmake-version: '3.21.x'

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
